### ISSUE TITLE
Plans for open-source release?

### ISSUE THREAD

**Issue by bdelepine** [SBRG/escher-fba-feedback#1]
Hi,

I was wondering out of curiosity if you were planning to somehow merge the features of Escher and Escher-FBA? If not, will you open Escher-FBA sources?

By the way, it is not clear to me how does Escher-FBA compare with [DD-DeCaF from Biosustain](https://app.dd-decaf.eu/app/pathwayvis) that used Escher to develop an interactive FBA too (among other features). Are you working together on this or are those two totally independent projects? I'm speaking only of the FBA feature of DD-DeCaF, of course.

Thank you for your awesome work on COBRApy-related tools. It's greatly appreciated!

Best,

**Comment by zakandrewking** [comment]
Sorry for the slow response. Just realized that my email notifications were not set up 😬

We do not currently have a plan to open up the source code of Escher-FBA or merge with Escher, but we might do that eventually (and we have other big plans that we hope to announce later in the year). 

In the meantime, DD-DeCaF is a good choice if you are looking for an open source tool. We do collaborate with the decaf team.

The main differentiator of Escher-FBA is that it's very lightweight and simple compared to decaf. Therefore, it's meant to complement decaf, particularly for anyone learning how FBA works for the first time.

I'm going to close the issue, but please let me know if you have any other questions.

zak
